# -*- coding: utf-8 -*-
"""10-Named_Entity_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WgIDLYYkc2TSCzNZxQELIARk-IPdDKI

### Named Entity Recognition:

It is the process of identifying andclassifying every entity in the text into the categories like:--

.    PERSON

.    ORG (Organization)

.    GPE (Location)

.    DATE

.    MONEY

.    PRODUCT

Example:

"Sundar Pichai is the CEO of Google."

Sundar Pichai --------------->    NAME

Google        --------------->    ORG (Organization)



#### Steps used in this Algorithm:----

1.  Import all the necessary libraries

2.  Load Pretrained NER Model

3.  Provide Sample Text

4.  Process the Text

5.  Extract all the Named Entities

6.  Show Only Text + Label (Cleaner Output)

7.  Visualize Entities

8.  Extract Specific Entity Types

9.  Real Industry Example (Resume Parsing Use Case)

### Step 1: Import all the necessary libraries
"""

import spacy

"""### **OBSERVATIONS:**

1.  spacy --------------> It is the library used in nlp for loading the NLP model and preprocessing the text.

### Step 2: Load Pretrained NER Model
"""

nlp = spacy.load("en_core_web_sm")

nlp

"""### **OBSERVATIONS:**

1. **en_core_web_sm** is a pre trained english model. It is used for
     
       (a.)     Tokenization

       (b.)     POS Tagging

       (c.)     Named Entity Recognition


2. The spacy library is passed through this pre trained english model and is used to process huge amount of datasets in it.

3.  It helps in improving the speed and the accuracy of the model.

### Step 3: Provide Sample Text
"""

text = """
Sundar Pichai is the CEO of Google.
He was born in Madurai, India in 1972.
Google is headquartered in California.
"""

text

"""### **OBSERVATIONS:**

1. The text comprises of three sentences.

### Step 4: Process the Text
"""

### convert the text into the object

doc=nlp(text)

doc

"""### **OBSERVATIONS:**

1. Here we begin with the preprocessing of the text.

2. The input text is converted into a Doc object.

3. Here the spacy can perform various operations with the input text like :-

    (a.)   Tokenization

    (b.)   POS Tagging

    (c.)   Document Parsing

    (d.)   Named Entity Recognition

### Step 5: Extract all the Named Entities
"""

doc.ents  ### detects all the named entities  in the text

for x in doc.ents:
  print("Entity Text is:", x.text)
  print("Entity Label is:", x.label_)
  print("Entity Starting Position is:", x.start_char)
  print("Entity Ending Position is:", x.end_char)
  print("-"*40)

"""### **OBSERVATIONS:**

1.  We have extracted all the named entities from the text.

2.  Then we have looped through all the named enetities.

3.  For every named entity, print the name, label, it's starting position and the ending position.

### Step 6: Show Only Text + Label (Cleaner Output)
"""

for i in doc.ents:
  print("Text is:", i.text)
  print("Labels is:", i.label_)
  print("-" * 40)

"""### **OBSERVATIONS:**

1.  We have extracted all the named entities from the text.

2.  For every named entity, we have extracted the text and the label for it.

### Step 7: Visualize Entities
"""

from spacy import displacy

displacy.render(doc, style = "ent", jupyter=True)

"""### **OBSERVATIONS:**

1. All the named entities have been highlighted in box.

### Step 8: Extract Specific Entity Types
"""

### extract all the entities whose label is 'Organization'

organizations = [(x.text) for x in doc.ents if(x.label_ == "ORG")]

organizations

"""### **OBSERVATIONS:**

1. Here we have obtained all the entities whose label is 'Organization'.

### Step 9: Real Industry Example (Resume Parsing Use Case)
"""

resume_text = """
Parag Pujari is a Data Scientist skilled in Python, SQL, Machine Learning and NLP.
He worked at Accenture and lives in Odisha.
"""

print(resume_text)


### convert the sample text into doc object

doc = nlp(resume_text)

print(doc)


### Get all the entities and the labels from the text

for x in doc.ents:
  print("Entity is:", x.text)
  print("Label is:", x.label_)
  print("-" * 40)

"""### **OBSERVATIONS:**

1. Here we have taken a sample text.

2. We have performed  the named entity recognition on the sample text.

3. Then we have extracted all the named entities from the text.

4. We have looped through all the named entities and extracted all the text and label for every named entity.
"""