# -*- coding: utf-8 -*-
"""9-Sentence_Embeddings_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yEhbZAezJGfOFmtoEt13SMOyzRkqRxf

#### **SENTENCE EMBEDDINGS:**

Sentence Embedding refers to the technique of converting the sentence text into the dense numerical vector that captures the semantic meaning.

It makes use of the context and semantics of the full sentence.


#### **Steps used in this Algorithm:--**

1.  Import all the necessary libraries

2.  Load the Pretrained Model

3.  Create the Sample Sentences

4.  Generate the  Sentence Embeddings

5.  Check the Embedding Shape

6.  View One Embedding

7.  Compute Similarity Between Sentences
"""

!pip install nbstripout
! nbstripout your_notebook.ipynb

import nbformat
from nbconvert.preprocessors import ClearOutputPreprocessor

# Load notebook
nb = nbformat.read("/content/9-Sentence_Embedding_NLP.ipynb", as_version=4)

# 1️⃣ Remove widgets metadata completely
if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

# 2️⃣ Clear all cell outputs
clear_output = ClearOutputPreprocessor()
nb, _ = clear_output.preprocess(nb, {})

# 3️⃣ Remove execution counts
for cell in nb.cells:
    if "execution_count" in cell:
        cell["execution_count"] = None

# 4️⃣ Remove cell metadata
    cell["metadata"] = {}

# 5️⃣ Remove notebook-level metadata except basics
nb.metadata = {
    "kernelspec": nb.metadata.get("kernelspec", {}),
    "language_info": nb.metadata.get("language_info", {})
}

# Save clean notebook
nbformat.write(nb, "9-Sentence_Embedding_NLP_GITHUB.ipynb")

print("🔥 Notebook fully cleaned for GitHub!")

"""### Step 1: Import all the necessary libraries"""

import  numpy            as   np
import  pandas           as   pd
import  matplotlib.pyplot as   plt
import  seaborn           as   sns

from    sentence_transformers      import SentenceTransformer
import  nltk

from    nltk.tokenize               import  sent_tokenize, word_tokenize
from    sklearn.metrics.pairwise   import cosine_similarity

"""### **OBSERVATIONS:**

1.  numpy -------------->  Computation of the numerical array

2.  pandas ------------->  Data Creation and Manipulation

3.  matplotlib --------->  Data Visualization

4.  seaborn ------------>  Data Correlation

5.  SentenceTransformer ------> loads a pre trained transformer model required for sentence embeddings

6.  sent_tokenize ----------->  converts the paragraphs into sentences

7.  word_toeknize ---------->  converts the sentences into words

8.  cosine_similarity ------->  get the similarity ratio between the sentences

### Step 2: Load the Pretrained Model
"""

### Load the Pre trained BERT Model

model = SentenceTransformer('All-MiniLM-L6-v2')

"""### **OBSERVATIONS:**

1.  **All-MiniLM-L6-v2** is a light weighted pre trained BERT Model.

2.  It produces 384 dimensional embeddings.

3.  It is fast and accurate for most of the tasks.


### **Why do we use the model here?**

1. The sentence embeddings requires BERT like pre trained transformer model.

2. It needs huge number of parameter for training.

3. It can be trained on massive datasets.

4. It requires huge computational power.

5. It produces high dimensional embeddings.

### Step 3: Create the Sample Sentences
"""

sentences = [
    "I love machine learning",
    "I enjoy studying artificial intelligence",
    "The weather is very hot today",
    "Deep learning is a branch of AI"
]

print(sentences)

"""### **OBSERVATIONS:**

1. A corpus is created that has four sentences.

### Step 4: Generate the  Sentence Embeddings
"""

### To generate the sentence embeddings

embeddings = model.encode(sentences, normalize_embeddings=True)

embeddings

"""###**OBSERVATIONS:**

1.  The sentence corpus is taken as an input.

2.  It is first tokenized

3.  Then it is passed through the transformer model.

4.  Max Pooling is performed

5. Then the fixed sized dense dimensional vectors is formed.

6. There were four sentences. After applying sentence embeddings on it,

    (a.)  It is converted into four rows. Each row has the dense dimensional vectors.

    (b.) There are a total of 384 dense dimensional vectors in each row.

### Step 5: Check the Embedding Shape
"""

print("Shape of the embeddings is:", embeddings.shape)

"""### **OBSERVATIONS:**

1. The shape of the sentence embeddings is (4, 384)

    (a.)   4   ---------->   sentences

    (b.)   384 ---------->   features

    So, the shape of the embeddings is (total sentences, total features)

### Step 6: View One Embedding
"""

print("First Embedding is:", embeddings[0])

"""###**OBSERVATIONS:**

1. It corresponds to the first sentence having 384 features.

2. It even depicts about the semantic meaning in the vector space.

### Step 7: Compute Similarity Between Sentences
"""

from sklearn.metrics.pairwise  import cosine_similarity

### get the similarity ratio between the sentences

similarity_matrix=cosine_similarity(embeddings)

similarity_matrix

"""### **OBSERVATIONS:**

1.  It depicts about the similarity ratio between the sentences in the corpus.

     Similarity ratio between sentence 1 and 1  ------>  1 (Totally same)
   
     Similarity ratio between sentence 1 and 2 -------> 0.56 (half same)

"""